package com.qicode.kakaxicm.kchat.db.dbmodel;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.qicode.kakaxicm.kchat.db.dbmodel.ConversationGreenDbObject;
import com.qicode.kakaxicm.kchat.db.dbmodel.MessageGreenDbObject;

import com.qicode.kakaxicm.kchat.db.dbmodel.ConversationGreenDbObjectDao;
import com.qicode.kakaxicm.kchat.db.dbmodel.MessageGreenDbObjectDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig conversationGreenDbObjectDaoConfig;
    private final DaoConfig messageGreenDbObjectDaoConfig;

    private final ConversationGreenDbObjectDao conversationGreenDbObjectDao;
    private final MessageGreenDbObjectDao messageGreenDbObjectDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        conversationGreenDbObjectDaoConfig = daoConfigMap.get(ConversationGreenDbObjectDao.class).clone();
        conversationGreenDbObjectDaoConfig.initIdentityScope(type);

        messageGreenDbObjectDaoConfig = daoConfigMap.get(MessageGreenDbObjectDao.class).clone();
        messageGreenDbObjectDaoConfig.initIdentityScope(type);

        conversationGreenDbObjectDao = new ConversationGreenDbObjectDao(conversationGreenDbObjectDaoConfig, this);
        messageGreenDbObjectDao = new MessageGreenDbObjectDao(messageGreenDbObjectDaoConfig, this);

        registerDao(ConversationGreenDbObject.class, conversationGreenDbObjectDao);
        registerDao(MessageGreenDbObject.class, messageGreenDbObjectDao);
    }
    
    public void clear() {
        conversationGreenDbObjectDaoConfig.clearIdentityScope();
        messageGreenDbObjectDaoConfig.clearIdentityScope();
    }

    public ConversationGreenDbObjectDao getConversationGreenDbObjectDao() {
        return conversationGreenDbObjectDao;
    }

    public MessageGreenDbObjectDao getMessageGreenDbObjectDao() {
        return messageGreenDbObjectDao;
    }

}
